title: Nighthawk Pages 
description: "Class of 2025"
owner_name: Tara Sehdave
github_username: tarasehdave
github_repo: "taraportfolio25" 
baseurl: "/taraportfolio25"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/tarasehdave/taraportfolio25"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" } 
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/game.md
  - navigation/blog.md
  - README4YML.md
  - navigation/search.md
